# Generated by Django 5.2.8 on 2026-03-03 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bd_models', '0009_ballinstance_deleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ping_role_id', models.BigIntegerField(blank=True, help_text='Optional role ID to mention in broadcast messages.', null=True)),
                ('config', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='broadcast', to='bd_models.guildconfig')),
            ],
            options={
                'db_table': 'broadcast',
                'managed': True,
            },
        ),
    ]
